/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as HrEsternoRouteImport } from './routes/hr-esterno'
import { Route as GrazieRouteImport } from './routes/grazie'
import { Route as CostoRouteImport } from './routes/costo'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as CheckUpRouteImport } from './routes/check-up'
import { Route as IndexRouteImport } from './routes/index'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEsternoRoute = HrEsternoRouteImport.update({
  id: '/hr-esterno',
  path: '/hr-esterno',
  getParentRoute: () => rootRouteImport,
} as any)
const GrazieRoute = GrazieRouteImport.update({
  id: '/grazie',
  path: '/grazie',
  getParentRoute: () => rootRouteImport,
} as any)
const CostoRoute = CostoRouteImport.update({
  id: '/costo',
  path: '/costo',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckUpRoute = CheckUpRouteImport.update({
  id: '/check-up',
  path: '/check-up',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-up': typeof CheckUpRoute
  '/cookie': typeof CookieRoute
  '/costo': typeof CostoRoute
  '/grazie': typeof GrazieRoute
  '/hr-esterno': typeof HrEsternoRoute
  '/metodo': typeof MetodoRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-up': typeof CheckUpRoute
  '/cookie': typeof CookieRoute
  '/costo': typeof CostoRoute
  '/grazie': typeof GrazieRoute
  '/hr-esterno': typeof HrEsternoRoute
  '/metodo': typeof MetodoRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-up': typeof CheckUpRoute
  '/cookie': typeof CookieRoute
  '/costo': typeof CostoRoute
  '/grazie': typeof GrazieRoute
  '/hr-esterno': typeof HrEsternoRoute
  '/metodo': typeof MetodoRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-up'
    | '/cookie'
    | '/costo'
    | '/grazie'
    | '/hr-esterno'
    | '/metodo'
    | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-up'
    | '/cookie'
    | '/costo'
    | '/grazie'
    | '/hr-esterno'
    | '/metodo'
    | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/check-up'
    | '/cookie'
    | '/costo'
    | '/grazie'
    | '/hr-esterno'
    | '/metodo'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckUpRoute: typeof CheckUpRoute
  CookieRoute: typeof CookieRoute
  CostoRoute: typeof CostoRoute
  GrazieRoute: typeof GrazieRoute
  HrEsternoRoute: typeof HrEsternoRoute
  MetodoRoute: typeof MetodoRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-esterno': {
      id: '/hr-esterno'
      path: '/hr-esterno'
      fullPath: '/hr-esterno'
      preLoaderRoute: typeof HrEsternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grazie': {
      id: '/grazie'
      path: '/grazie'
      fullPath: '/grazie'
      preLoaderRoute: typeof GrazieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costo': {
      id: '/costo'
      path: '/costo'
      fullPath: '/costo'
      preLoaderRoute: typeof CostoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-up': {
      id: '/check-up'
      path: '/check-up'
      fullPath: '/check-up'
      preLoaderRoute: typeof CheckUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckUpRoute: CheckUpRoute,
  CookieRoute: CookieRoute,
  CostoRoute: CostoRoute,
  GrazieRoute: GrazieRoute,
  HrEsternoRoute: HrEsternoRoute,
  MetodoRoute: MetodoRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
