/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as HrEsternoRouteImport } from './routes/hr-esterno'
import { Route as CostoRouteImport } from './routes/costo'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as IndexRouteImport } from './routes/index'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEsternoRoute = HrEsternoRouteImport.update({
  id: '/hr-esterno',
  path: '/hr-esterno',
  getParentRoute: () => rootRouteImport,
} as any)
const CostoRoute = CostoRouteImport.update({
  id: '/costo',
  path: '/costo',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie': typeof CookieRoute
  '/costo': typeof CostoRoute
  '/hr-esterno': typeof HrEsternoRoute
  '/metodo': typeof MetodoRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie': typeof CookieRoute
  '/costo': typeof CostoRoute
  '/hr-esterno': typeof HrEsternoRoute
  '/metodo': typeof MetodoRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookie': typeof CookieRoute
  '/costo': typeof CostoRoute
  '/hr-esterno': typeof HrEsternoRoute
  '/metodo': typeof MetodoRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cookie' | '/costo' | '/hr-esterno' | '/metodo' | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cookie' | '/costo' | '/hr-esterno' | '/metodo' | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/cookie'
    | '/costo'
    | '/hr-esterno'
    | '/metodo'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookieRoute: typeof CookieRoute
  CostoRoute: typeof CostoRoute
  HrEsternoRoute: typeof HrEsternoRoute
  MetodoRoute: typeof MetodoRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-esterno': {
      id: '/hr-esterno'
      path: '/hr-esterno'
      fullPath: '/hr-esterno'
      preLoaderRoute: typeof HrEsternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costo': {
      id: '/costo'
      path: '/costo'
      fullPath: '/costo'
      preLoaderRoute: typeof CostoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookieRoute: CookieRoute,
  CostoRoute: CostoRoute,
  HrEsternoRoute: HrEsternoRoute,
  MetodoRoute: MetodoRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
